apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: keycloak-config-patch.yaml
    target:
      kind: ConfigMap
      name: keycloak-config
  - path: web-frontend-config-patch.yaml
    target:
      kind: ConfigMap
      name: web-frontend-config
