apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: postgres-pdb
  namespace: chess
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: postgres
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: mongodb-pdb
  namespace: chess
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: mongodb
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: kafka-pdb
  namespace: chess
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: kafka
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: rest-api-pdb
  namespace: chess
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: rest-api
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: keycloak-pdb
  namespace: chess
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: keycloak
