apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: chess
type: Opaque
stringData:
  POSTGRES_USER: chess_user
  POSTGRES_PASSWORD: chess_password
  POSTGRES_DB: chess
  POSTGRES_MULTIPLE_DATABASES: keycloak
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secret
  namespace: chess
type: Opaque
stringData:
  KEYCLOAK_ADMIN: admin
  KEYCLOAK_ADMIN_PASSWORD: admin123
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: chess
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: ""
  MONGO_INITDB_ROOT_PASSWORD: ""
  MONGO_INITDB_DATABASE: chess
---
apiVersion: v1
kind: Secret
metadata:
  name: lichess-secret
  namespace: chess
type: Opaque
stringData:
  LICHESS_API_TOKEN: "REPLACE_WITH_LICHESS_BOT_TOKEN"
