name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout (merge)
        uses: actions/checkout@v3
        if: github.event_name != 'pull_request'
        with:
          fetch-depth: 0

      - name: Git checkout (PR)
        uses: actions/checkout@v3
        if: github.event_name == 'pull_request'
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run tests with coverage
        run: sbt clean coverage test

      - name: Upload coverage to Coveralls
        run: sbt coverageReport coveralls
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
